language: node_js
node_js:
- '10'
cache: npm
script: 'true'
deploy:
  provider: heroku
  api_key:
    secure: DKMsv5Gt9fV1O8Gz2VQ0b4LFSCHQD9fOTCN4PRxrB029GZucV0VTM9MBbu+LJXyeHB8lTK9Af4Z38YGLnk7iDo+wRZdLFlr+BzJpFw3LDlmcSLxPZIRJmQzQMkxnrjDrVkDG1/mGO+wjee1zKBU/pABeu2ANlopJOLKMjYZt9NuK0dquXYEetweviTeI6f2v0I9lftJm9lPvBpK1pJC0w6FNzQgGGTBchzW8NfUWFTUc1olNrjwMbTHl/+t0Cmg0VRRMKHTX2KNpUfoMoRui1tVAoiZWDAYikRJvrs1eMhEyCb/+SbpC45XAvydsjgrutnordYw5PyAyaqmNqbwBvzJghD314Ga1eGwUXM49TO97FO3rg9uN45+4AHcNJWE4pQs/vHtSIt2ZyKaLiWYPicVd8d6KQPYI2ajeA+L4a4Iup1kEA3koXLDo/Xmey4+GEYycBFnSBKmkYnGE7sUBPjm+1GpNDW0kjp0DfbVZNL7Ki9JpD+ad7QjWRVesAXIrPJY93WzG/9T6wLqkewJBKR4ml1fb36shBYXFI5pOTVcZd0aFVWZFRgLQghQ/T2y+w5AEKqpej/GRk+/x0EJzwG9fQRMwvICL7HNvIby/2KxAsFgMNVcnooZ8tBvRM8tkTzdyBntEMKDE8xEwuT1osEgyiHlgXhnXNHCUb2HmQG4=
