language: node_js
node_js:
- "10"
cache: npm

script: 'true'

deploy:
  provider: heroku
  api_key:
    secure: "K70OczBB5goj4silndnhGEGzLk1SOcIGPwc16tP0Qb4nqxZSJYPk89PKmVEKkr0K6qopz8jDrOL9UuoNulR0Qh/GblTTwECVCFS1Y2SsJZBDMX3d0/TKoLnQBuAghJMfFllFVF0uE5TQbm3VEVXF4c28qRPEaCapkVKfMze0jSaRV6lDNLwp0pCqsQDMwfXmZZdQf2KSBH1R/LmSBuDaPWc9oKGEps+DDBIUGU8cYyu5j1wUUV3N9r+d/Ja+uT4cmiaPQV0eTVv9wCMfhFPmIY+Oat0fiDKIIHFCBJRVZGYpBr18naGAAMjKqPSdX7Dhz33W1/RR/iOlPaW28GxZ6EwbBj+ChqHj350KeYEqrdmg1W0ifGwS+aacU7IsL/AXVgP2fm2dlYD5HRc+TR9djvz6w92x7w4oPXz34U95vsFtTylweM3MVwJO3sKgnTtf9yXQeHuSWgWkoG87hYF89Stp9d/8VZhmyj6TQE2NOY2Oguf5ABlefrGMN9UBel88qLntLZ3b9wYXNig4IA/+8m8HkQn2LoDPfv5tJ6zbRHdam7cinn1M4N43w18Z87grhN3d2kGgA+L5J7c9Jdx+BJg+VbH7j4x2k/aPaNqol74ldlddYu+eRcnq/HdVJC8wunwKvjUokb0Tt3rDD7u/o8rFM/GOPoLLy8jVyE95wkc="