language: node_js
node_js:
- '10'
cache: npm
script: 'true'
deploy:
  provider: heroku
  api_key:
    secure: jwMcHeAOTvdHGVieG0BwuuMbcVDJae2g/4VPVUXm8sqeiYhSZCaR3WpD43mm2+SlIOuLZqnv5YQ6kgluKtGcLRNBDJgNuHcVH2bhr6hICpl97MvbKfKbUiqHWvXggRyVzmnIsZsK0ZpXYlPmjPJZcsRZ3VnICd2G7dR+fLtz/Oac9qhoVlE4wFDJ4pLXF6P4ekWD4t++j9dtgXjMjLdgo+NiD7xcUnJDzyLvwA19aY4NF6WTTrEKBOaIuMuKOlsJ5Vark3EkGI4yrq5Iz4JqdXJo7/k0tLqwsj9GaPwvoKt70/3xZXFTVHny3dn1hPhGHm9PWLsyHRYPJVoF1eTTr1nJOwAi6TMOFRGl+BhgRsp7wZTld/crC9Koxjxhl47L4OHW27HunD8Ih7ueqdiUhq6qf32sAbFA5V0QNt+i+vAxPR5tmHMo6EdmXID7/OZNRqCjYtgzbgRJo2ZV5c168Xm+24xM+qSGCRsYJqJUHTRR9xflGx8DsmDbuCkSzWrVSbvPaErO9qMMyp4H2PTBaFppa9ZmBe26mckJuFCiYiS8penDvNP6uqariTaMSbdeNJLQBrQxrssE5Grl8GldczxoPPLE04H/I3jASYQ5yObjN6cDqV/bnrCZkyZgQtiO7Ea+HIwyUP4u8rGra7aJlTx0Noo93u4VHSHIKMqrvqc=
  app: vwatch0